name: Misc

on:
  workflow_dispatch:

  push:
    branches: 
      - master
    paths:
      - '.github/workflows/Misc.yml'
  schedule:
    - cron: '0 * * * *'

jobs:
  rules:
    name: Update rules from other repos
    runs-on: ubuntu-latest
    steps:
    - name: Update
      env:
        TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email actions@github.com
        mkdir repo && cd repo && git init
        git clone -b master https://github.com/DivineEngine/Profiles.git DivineEngine
        rm -rf DivineEngine/.git
        git clone -b master https://github.com/lhie1/Rules.git lhie1
        rm -rf lhie1/.git
        git clone -b master https://github.com/blackmatrix7/ios_rule_script blackmatrix7
        rm -rf blackmatrix7/.git
        git clone -b master https://github.com/NobyDa/Script NobyDa
        rm -rf NobyDa/.git
        git clone -b master https://github.com/chavyleung/scripts chavyleung
        rm -rf chavyleung/.git
        git add . && git commit -m "Update"
        git remote add origin https://Apocalypsor:$TOKEN@github.com/$GITHUB_REPOSITORY.git
        git push -f origin master:Misc
        
