name: Update

on:
  workflow_dispatch:

  push:
    branches: 
      - master
    paths:
      - '.github/workflows/*.yml'
  schedule:
    - cron: "0 */6 * * *"

jobs:
  dns:
    name: 90DNS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Create local changes
      run: |
        curl -sS https://gitlab.com/a/90dns/-/raw/master/dnsmasq/dnsmasq.conf > /tmp/dnsmasq.conf
        sed -i -e "/^interface.*/d" -e "s/address=\//DOMAIN,/g" -e "s/DOMAIN,\./DOMAIN-SUFFIX,/g" -e "s/\/127.0.0.1/,REJECT/g" -e "s/\/[0-9].*/,DIRECT/g" /tmp/dnsmasq.conf
        grep ".*DIRECT" /tmp/dnsmasq.conf | sed -e "s/^DOMAIN,/  - '/g" -e "s/^DOMAIN-SUFFIX,/  - '+./g" -e "s/$/'/g" -e "s/,DIRECT//g" -e "1i\payload:" > ./Clash/90dns_direct_provider.yml
        grep ".*REJECT" /tmp/dnsmasq.conf | sed -e "s/^DOMAIN,/  - '/g" -e "s/^DOMAIN-SUFFIX,/  - '+./g" -e "s/$/'/g" -e "s/,REJECT//g" -e "1i\payload:" > ./Clash/90dns_reject_provider.yml
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update 90DNS
        skip_dirty_check: false

  china_ip:
    name: China IP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Create local changes
      run: |
        curl -sS https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt > /tmp/china_ipv4.txt
        curl -sS https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt > /tmp/china_ipv6.txt
        echo "" > /tmp/blank && cat /tmp/china_ipv4.txt /tmp/blank /tmp/china_ipv6.txt > /tmp/china_ip.txt
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e "1i\payload:" /tmp/china_ipv4.txt > ./Clash/china_ipv4.yml
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e "1i\payload:" /tmp/china_ipv6.txt > ./Clash/china_ipv6.yml
        sed -e "s/^/  - '/g" -e "s/$/'/g" -e "1i\payload:" /tmp/china_ip.txt > ./Clash/china_ip.yml
        sed -e "s/^/IP-CIDR,/g" /tmp/china_ipv4.txt > ./Surge/IPDB/china_ipv4.list
        sed -e "s/^/IP-CIDR,/g" /tmp/china_ipv6.txt > ./Surge/IPDB/china_ipv6.list
        sed -e "s/^/IP-CIDR,/g" /tmp/china_ip.txt > ./Surge/IPDB/china_ip.list
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update China IP
        skip_dirty_check: false

  ublacklist:
    name: uBlacklist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Create local changes
      run: |
        curl -sS https://raw.githubusercontent.com/cobaltdisco/Google-Chinese-Results-Blocklist/master/uBlacklist_subscription.txt > /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/liubiantao/uBlacklist-Websites/master/uBlacklist.txt >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/DivineEngine/uBlacklist/master/blacklist.txt >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/YeSilin/uBlacklist/master/list.txt >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/MisakaMikoto-35c5/ublacklist-rules/master/content-farm.txt >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/MisakaMikoto-35c5/ublacklist-rules/master/bad-content.txt >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/lbydev/uBlacklist/master/blacklist.txt >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/gyli/Blocklist/master/BLOCKLIST | sed -e "s/^/*:\/\/*./g" -e "s/$/\/*/g" >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/scyrte/uBlacklist-Subscription/master/blacklist.txt >> /tmp/list && echo "" >> /tmp/list
        curl -sS https://raw.githubusercontent.com/proudust/uBlacklist-Subscription/master/blacklist.txt >> /tmp/list && echo "" >> /tmp/list
        cat uBlacklist/Extra.txt >> /tmp/list
        cat /tmp/list | sed -e "s/^!.*//g" -e "s/^ *Update.*//g" -e "s/^#.*//g" -e "s/\*\.www\./*./g" -e "/^$/d" | sort -u > uBlacklist/uBlacklist.txt
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update uBlacklist
        skip_dirty_check: false
